// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGConsts
{
        public const string achievement_pikachu_onet_connect_2 = "CgkI3rmjsbcREAIQCw"; // <GPGSID>
        public const string achievement_pikachu_onet_connect_3 = "CgkI3rmjsbcREAIQDA"; // <GPGSID>
        public const string achievement_pikachu_onet_connect_4 = "CgkI3rmjsbcREAIQDQ"; // <GPGSID>
        public const string leaderboard_challenge_mode_hard = "CgkI3rmjsbcREAIQBg"; // <GPGSID>
        public const string leaderboard_time_mode_normal = "CgkI3rmjsbcREAIQAg"; // <GPGSID>
        public const string leaderboard_challenge_mode_normal = "CgkI3rmjsbcREAIQBw"; // <GPGSID>
        public const string leaderboard_time_mode_hard = "CgkI3rmjsbcREAIQAw"; // <GPGSID>
        public const string leaderboard_survival_mode_normal = "CgkI3rmjsbcREAIQAA"; // <GPGSID>
        public const string leaderboard_leisure_mode_normal = "CgkI3rmjsbcREAIQBQ"; // <GPGSID>
        public const string achievement_pikachu_onet_connect = "CgkI3rmjsbcREAIQCQ"; // <GPGSID>
        public const string leaderboard_survival_mode_hard = "CgkI3rmjsbcREAIQAQ"; // <GPGSID>
        public const string leaderboard_leisure_mode_hard = "CgkI3rmjsbcREAIQBA"; // <GPGSID>
        public const string achievement_pikachu_onet_connect_1 = "CgkI3rmjsbcREAIQCg"; // <GPGSID>

}

